[book]
title = "whamm! (ฉบับภาษาไทย)"
description = "แนะนำภาษา DSL ของ `whamm!` ฉบับภาษาไทย"
authors = ["ahuoguo", "ejrgilbert", "wavid-b"]
language = "th"
src = "src"

[output.html]
default-theme = "rust"
preferred-dark-theme = "ayu"
git-repository-url = "https://github.com/suradet-ps/whamm-th/tree/main/docs/src"
edit-url-template = "https://github.com/suradet-ps/whamm-th/edit/main/docs/{path}"
no-section-label = false

[output.html.search]
enable = true
limit-results = 30
boost-title = 2
boost-hierarchy = 1
